### ISSUE TITLE
The action is failing because the PR information is missing

### ISSUE THREAD

**Issue by ikerexxe** [linuxdeepin/action-cppcheck#3]
The cppcheck action seems to be executing correctly until it tries to report the errors in the PR. Then, some information for the PR is missing and it fails.

```
2022/03/14 14:00:55 POST https://api.github.com/repos/SSSD/sssd/pulls/5762/reviews: 422 Unprocessable Entity [{Resource: Field: Code: Message:Pull request review thread line must be part of the diff and Pull request review thread diff hunk can't be blank}]
Error: Process completed with exit code 1.
```

For further information you can check the [full log](https://github.com/SSSD/sssd/runs/5538384367?check_suite_focus=true#step:3:1570).

**Comment by ikerexxe** [comment]
It seems like the PR metadata is malformed.

**Comment by myml** [comment]
Thank you for your feedback. Fixed by https://github.com/linuxdeepin/action-cppcheck/pull/5
Test result https://github.com/myml/sssd/runs/5549045328?check_suite_focus=true
Please use v0.0.10 version
